### ISSUE TITLE
为什么数据里面最后放电的倍率是2C ？

### ISSUE THREAD

**Issue by myalos** [HAIRLAB/Health_status_prediction#3]
感谢分享数据和代码，随机抽了三个数据进行了细致的分析，发现放电的最后一个阶段 并不是按照论文里面提到的1C（1100mA)，而是2200mA 2C，电池10-2 里面的放电数据里面没有放电电流为1100mA的

**Comment by myalos** [comment]
还有一个问题想要请教 数据里面
                            Status  Cycle number  Current (mA)  Voltage (V)  Capacity (mAh)  Time (s)
0          Constant current charge             2       5497.39       2.8338        0.000000         0
1          Constant current charge             2       5497.39       3.2533        7.635264         4
2          Constant current charge             2       5497.39       3.5165       15.270528         9
7.63 应该是5秒的5500mA左右积分积出来的，9s的5500mA左右积分积出来算出来是13.74，数据不一致

**Comment by mxt0607** [comment]
您好，我们仔细检查了数据，您说的是对的，放电的第四段放电率均为2C，以数据给出的2C为准。谢谢！

**Comment by mxt0607** [comment]
您好，我们仔细检查了数据，您说的是对的，放电的第四段放电率均为2C，以数据里的2C为准。谢谢！

**Comment by myalos** [comment]
收到 感谢回复
