### ISSUE TITLE
Issue with reproducing results for Task 2 using 2-ne2wx.ipynb

### ISSUE THREAD

**Issue by hilinxinhui** [HAIRLAB/Health_status_prediction#4]
Hi there, thank you for the remarkable work with this project. However, I've encountered an issue while attempting to replicate the results for Task 2, specifically when executing the 2-ne2wx.ipynb notebook. 

While I was able to achieve the expected outcomes using the pre-trained models provided in this repository, I faced challenges when attempting to re-pretrain and fine-tune the models for online adaptation in the target domain. The performance of the model in the target domain was poor, as illustrated in the attached screenshot below.

I ensured to maintain the version of torch as specified in the README document. However, due to some version conflicts, I had to opt for newer versions of scipy (1.10.1) and numpy (1.24.4). I also experimented with different random seeds in an attempt to isolate the issue. Despite these efforts, I'm unsure what could be causing this degradation in performance. Could you please offer any advice or suggestions that might help address this issue? 

![image](https://github.com/user-attachments/assets/86c8fc74-dfcc-43a0-b440-235ec00c51c4)

**Comment by mxt0607** [comment]
Thanks for your attention. The current version has not been updated. If you are interested in training the model from the scratch, the aux_factor = 1190 (mAh) should be divided by 1000 (Ah) in the file of “prepare_ne_data.py”.

**Comment by hilinxinhui** [comment]
Thank you for your timely and helpful response, the issue above has been resolved.
